name: Build Container

on:
  workflow_dispatch:
    # inputs:
    #   environment:
    #     description: "environment"
    #     required: true
    #     type: environment
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"


      - name: virtual-kubelet
        uses: docker/build-push-action@v6
        with:
          file: docker/virtual-kubelet/Dockerfile
          build-args: 'VERSION_FLAGS=-ldflags=-X main.buildVersion=1.6.2 -X main.buildTime=2025-04-28T16:49:55'
          push: true
          tags: reg2.redhive.me/${{ env.REPO }}:latest

      - name: init-container
        uses: docker/build-push-action@v6
        with:
          file: docker/init-container/Dockerfile
          push: true
          tags: reg2.redhive.me/${{ env.REPO }}:latest
